version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=scraping
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network
    command: ["--bind_ip", "0.0.0.0"]

networks:
  mongo-compose-network:
    driver: bridge